### ISSUE TITLE
S4 Handelsschiff Teleportbug

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#14]
Wenn ein Handelsschiff Waren zu einem Zielhafen transportieren soll, der nicht an der gleichen Wasserfläche liegt, lädt das Schiff die Waren ein und ohne sich zu bewegen direkt wieder am Zielhafen aus. Die Waren werden gewissermaßen teleportiert. Der Bug muss absichtlich hervorgerufen werden und ist sehr leicht replizierbar.

**Comment by kdsystem1337** [comment]
Duplicate
