### ISSUE TITLE
S4 Baubug

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#18]
Beim Bauprozess eines Gebäudes kann es passieren, dass die Bauarbeiter gar nicht erst anfangen es zu hämmern, oder bei 99% aufhören, sodass das ganze Baumaterial verbaut ist, aber das Gebäude immer noch als Baustelle da steht und nicht als fertiges Gebäude.

**Comment by kdsystem1337** [comment]
Fehlerbehebung durch @JHNP727
Getestet durch @kdsystem1337 und @itsRobStar.
