### ISSUE TITLE
S4 Trojaner Minenbatteriebug

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#20]
Wenn auf gestoppte Minen der Köstlichkeiten-Zauber angewendet wird, wird die gezauberte Nahrung erst von Trägern abgeholt, nachdem die Mine gestartet und wieder gestoppt wurde.

**Comment by kdsystem1337** [comment]
Fehlerbehebung durch @JHNP727 
Test steht noch aus.

**Comment by kdsystem1337** [comment]
Test durchgeführt. Funktioniert wunderbar
