### ISSUE TITLE
S4 Singleplayer lobby buggt

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#35]
**EDIT**
Bekannter Bug von Ubisoft: Singleplayer Lobby von Siedler IV
In einer SIngleplayer Lobby von SIedler IV kann nach dem Positionswechsel keine Einstellung mehr vorgonommen werden. 
Umgehungslösung: Erst alles einstellen (auf die Namen der (Computer-)Spieler klicken) und dann die Position als letztes Wählen. Hat man sich verdrückt kann man mit ESC das menü verlassen.

----------------------------------
 Known bug from Ubisoft: Settlers IV Singleplayer Lobby
In a Settlers IV SIngleplayer lobby, no settings can be made after the position change. 
Workaround: First set everything (click on the names of the (Computer-)players) and then select the position last. If you have lost your way, you can leave the menu by pressing ESC.

**ORG**
Wenn man in Singleplayer Lobbies seine Position ändert, lassen sich keine Einstellungen mehr vornehmen und man kann die Lobby auch nicht mehr verlassen. Man nur noch das Spiel starten, oder sich selber aus der Lobby kicken, was zu einem FE  führt.

**Comment by kdsystem1337** [comment]
Als Bekannter Bug auf SU geführt:
![image](https://user-images.githubusercontent.com/65427854/153772835-518020c6-ae24-46dc-83fc-a63c6b21fbb5.png)

**Comment by kdsystem1337** [comment]
Auch ist dies ein Bug wenn man zu schnell (doppelt) eine Lobby aufmacht, dann ist der State defekt:
![image](https://user-images.githubusercontent.com/65427854/175942265-86e33a62-d81f-4858-876f-4d88fad1a433.png)

**Comment by kdsystem1337** [comment]
Behoben mit 0.9.145 (Preview) von @WizzardMaker und implementierung in SU Plugin durch @kdsystem1337
