### ISSUE TITLE
S4 Angriffsschnelligkeit unterschiedlich

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#41]
Die Angriffsschnelligkeit der Maya-Bogenschützen Level 3 ist leicht langsamer, als die der anderen Völker. Das gleiche gilt für die Wikinger-Schwertkämpfer Level 1.

**Comment by kdsystem1337** [comment]
Trojaner L3 und Maya Bögen L2/L1 möglicherweise auch.

**Comment by kdsystem1337** [comment]
siehe auch https://github.com/settlers-united/orga/issues/70
