### ISSUE TITLE
S4 Spielgeschwindigkeit Ingame mit Cheats erhöhen

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#56]
Die Spielgeschwindigkeit Ingame mit Cheats erhöhen geht nicht. Im Grundspiel ist das problemlos möglich.

**Comment by janwendt** [comment]
@itsRobStar das gilt nur für den Singleplayer, korrekt?

**Comment by kdsystem1337** [comment]
Behoben mit der Kommenden SU Version 0.9.145 (Preview)

@itsRobStar @UltimateSpinDash
