### ISSUE TITLE
S4 Lagerbug (Slotbug) [1]

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#7]
Bei Lagern kann es passieren, dass manche Slots verbuggen, sodass die Waren in diesen Slots weder ein- noch ausgelagert werden. Die restlichen Slots des Lagers funktionieren dennoch weiter einwandfrei. Der Bug ist random und nicht leicht reproduzierbar. Ein Savegame liegt nicht vor.

**Comment by kdsystem1337** [comment]
Möglicherweise hier im save enthalten
[Lagerbug_Slotbug.zip](https://github.com/settlers-united/orga/files/7591373/Lagerbug_Slotbug.zip)

**Comment by kdsystem1337** [comment]
Hier im Save enthalten:
[LagerBug_KeinHolzAuslagern.zip](https://github.com/settlers-united/orga/files/7672132/LagerBug_KeinHolzAuslagern.zip)

**Comment by itsRobStar** [comment]
Hier ebenfalls ein weiterer Save mit dem Bug
[JSHC7V80_autoSave_A.zip](https://github.com/settlers-united/orga/files/7735849/JSHC7V80_autoSave_A.zip)

**Comment by kdsystem1337** [comment]
Hier ein erneuter Save für bessere Reproduzierbarkeit:
[Lagerbug.zip](https://github.com/settlers-united/orga/files/9125394/Lagerbug.zip)

**Comment by kdsystem1337** [comment]
Venaric TV — heute um 17:31 Uhr
S4: Lagerbug Ursache: Eine Ware aus dem Lager wird von einem Gebäude angefragt. Das Gebäude wird jedoch pausiert, noch bevor ausgelagert wird -> Ware verbuggt
kann auch noch andere Ursachen geben, aber die funktioniert bisher immer

**Comment by kdsystem1337** [comment]
Venaric TV — heute um 17:35 Uhr
ja, stapel scheint dann verbuggt, kann noch aufgefüllt werden, aber nicht mehr geleert

**Comment by kdsystem1337** [comment]
``` @fbreuss 
Der Lagerbug tritt auf wenn ein Stapel im Lager aufgebraucht werden würde, es aber dann doch nicht wird (das zu bauende Gebäude wird pausiert/abgerissen).
Der Warenstapel wird dabei aus dem Wirtschaftssektor genommen und im Fall vom Lager nicht wieder zurück rein getan wenn das zu bauende Gebäude pausiert/zerstört wird. Dadurch trägt es danach niemand mehr weiter und es bleibt für immer im Lager 🤔
Bei normalen Stapel passiert das nicht weil genau für diese Funktionalität eine andere Funktion je nach Stapel-Typ aufgerufen wird.
```

Fixed by fbreuss in 0.9.169 (Experimentell)
