### ISSUE TITLE
S4 Schiffe FE

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#8]
Es wurde häufig beobachtet, dass in Runden, in denen Schiffe benutzt wurden zu einem bestimmten Zeitpunkt, der jedoch von Spiel zu Spiel variiert, immer wieder ein FE kommt. Absichtlich kann man den Bug eher schwierig hervorrufen. Ein Savegame, wo dieser Bug stark vermutet wird, liegt vor.

**Comment by kdsystem1337** [comment]
[Uploading SchiffeFE.zip…]()
Hier der Save von @itsRobStar

**Comment by fbreuss** [comment]
Der FE im Save "SchiffeFE.zip" tritt auf, weil auf Speicher außerhalb des EntityPools zugegriffen wird, genau wenn das mittlere große Wohnhaus vom weißen Spieler fertig wird, das sich zu Beginn bereits am Bildschirm befindet.

Er tritt *nicht* mehr mit aktivem SU auf...

**Comment by kdsystem1337** [comment]
@fbreuss dann ist das erledigt?

**Comment by fbreuss** [comment]
Mit diesem Save ja.
Aber FEs wo vmtl. Schiffe der Grund sind, sind trotzdem nicht auszuschließen...
