### ISSUE TITLE
S4: After closing S4 using in-game exit-button, not possible to open again using Settlers United client, as it registers as still running.

### ISSUE THREAD

**Issue by MarcusTalbotS** [settlers-united/orga#80]
Expected behaviour:
After closing S4 using the in-game exit-button, it should be possible to start the game again using the SU-client.

Observed behaviour:
After closing S4, the SU throws an error when trying to launch the game again.
![exit_bug](https://user-images.githubusercontent.com/90057025/180465263-d367ae40-b843-49c4-aaa2-eab34dfe4b52.png)

Steps to reproduce:

1. Open the SU-client.
2. Start S4 in Singleplayer-mode.
3. Exit the game using the in-game Exit-button.
4. Attempt to start S4 again using the SU-client, in singleplayer-mode.
5. Client should throw an error.

**Comment by MarcusTalbotS** [comment]
The bug only occurs when not logged in with Discord. If the user is logged in using Discord, the client works as expected; the game can be exited and restarted at will.

**Comment by Id3aFly** [comment]
It would still be awesome to remove this bug, as many players maybe don't use Discord.

**Comment by kdsystem1337** [comment]
Should have been fixed with the next version. If you try to start Settlers IV again while logged in, this will generate some error messages.

**Comment by kdsystem1337** [comment]
fixed with next release (0.9.94), release pending.
