### ISSUE TITLE
S4: Marketplace Deadlock - Two carts, same route

### ISSUE THREAD

**Issue by Gizzmicbob** [settlers-united/orga#84]
Normally it seems like only one donkey can use a trade/transport route. When removing and re-adding a trade route, sometimes a second donkey can "take over" a trade route while the first donkey still delivers goods.
This can sometimes cause a deadlock when the first donkey unloads and then stops moving - likely due to the second donkey "owning" the trade route and only one donkey is allowed per trade route.

![image](https://user-images.githubusercontent.com/15408031/229414016-7d11d4c2-fd7d-4306-98c3-2f36fb1782c3.png)

Removing and re-adding a trade route does not fix the deadlock.
Destroying the marketplace seems to make the donkey forever stuck in limbo. If the donkey doesn't have a cart, it's impossible to remove it.

A donkey stuck in limbo seems to be able to deadlock other donkeys if it gets in their way. Once deadlocked, same as with the stuck-in-limbo donkey, they cannot be fixed.

**Comment by kdsystem1337** [comment]
Thanks for the report. The errors are collected here #40
