### ISSUE TITLE
S4: Marketplace random deadlock

### ISSUE THREAD

**Issue by Gizzmicbob** [settlers-united/orga#86]
Over time, donkeys will randomly deadlock at a marketplace with seemingly no reason. The only way to fix it is to remove the trade route and then re-add it, but this causes the donkey to move to another trade route and either join that one or come back to the original trade route (with no goods) after moving to a different marketplace.

![image](https://user-images.githubusercontent.com/15408031/229417575-5725f8ca-c1e3-4f8d-8a49-be440f1e5bf9.png)

This seems much more likely to occur with multiple donkeys even if they use different trade routes and never get in each other's way.

Sometimes after attempting to fix the deadlock and the donkey moving to a new marketplace, it will also deadlock in the new marketplace. This will sometimes fix itself when another donkey moves from their marketplace.

**Comment by Gizzmicbob** [comment]
Sometimes forcing another donkey to move immediately (switching from infinite to 0) makes a deadlocked donkey move.
The "other" donkey is on a completely different trade route but it seems the first donkey switches to the trade route of the second donkey afterwards... Need to see how consistent this is.

**Comment by kdsystem1337** [comment]
The errors are collected here #40
