### ISSUE TITLE
S4: Trade ships can overflow a habour

### ISSUE THREAD

**Issue by Gizzmicbob** [settlers-united/orga#89]
![image](https://user-images.githubusercontent.com/15408031/229433599-71577b2e-05f4-4ffc-9766-03fd1ab279d4.png)

The image explains it pretty well

**Comment by Gizzmicbob** [comment]
![image](https://user-images.githubusercontent.com/15408031/229438244-a446eb11-72fa-488c-97b3-5e7a1fea99d7.png)

One of the ships keeps incrementing the amount of logs it's holding. The 1000s number is going up 7 every second. My production menu does not see this change in number.

**Comment by kdsystem1337** [comment]
Thanks for the report, the problem was already tracked in #2 .
