### ISSUE TITLE
S4 Priobug

### ISSUE THREAD

**Issue by itsRobStar** [settlers-united/orga#9]
Exzessive Benutzung der Prio-Funktion kann dazu führen, dass kein Gebäude mehr gebaut wird, außer alle offenen Baustellen werden priorisiert. Ein Savegame liegt inzwischen vor

**Comment by janwendt** [comment]
Das ist der Grund warum ich kein S4 spiele. Absolut unerträglich! Deshalb Priorität "high"

**Comment by kdsystem1337** [comment]
@janwendt Prio wurde erhöht da nun ein Save gefunden wurde!
[PrioBug_KeinSteinTragen.zip](https://github.com/settlers-united/orga/files/7672300/PrioBug_KeinSteinTragen.zip)

**Comment by kdsystem1337** [comment]
[PRIO_BUG.zip](https://github.com/settlers-united/orga/files/7677891/PRIO_BUG.zip)
Hier ein Save, es hat etwas mit mehr als 9 Baustellen die auf prio sind zu tun, diese Verbuggen sich (die Prio wird weggenommen nachdem sie den current State verlassen und nicht mehr gesetzt)

**Comment by kdsystem1337** [comment]
Behoben mit Version 0.9.34

**Comment by kdsystem1337** [comment]
[1-priobug.zip](https://github.com/settlers-united/orga/files/7697461/1-priobug.zip)
