### ISSUE TITLE
small typo im Wiki

### ISSUE THREAD

**Issue by mcRentner** [settlers-united/orga#90]
kleiner Rechtschreibfehler im DE Wiki.
2ter Absatz,
erste Zeile,
letztes Wort
[[](url)](https://docs.settlers-united.com/v/s4-lua-api-de/tutorials/aller-anfang/entrypoint-register_functions-events-1)

**Comment by kdsystem1337** [comment]
Danke für die meldung, durch @UltimateSpinDash behoben
